import { parseBodyPart, type BodyPart } from "./BodyPart";

/**
 * Body parts off the Iloilo used market: the lip everyone's barkada has, a pull-out ducktail, the
 * marketplace GT wing that's wider than the trunk, a bumper nobody got around to painting, a
 * fender off a red Dalagan and the carbon-look hood with pins. Numbers are against the Banwa
 * Dalagan's stock panels.
 */
export const BODY_PARTS: readonly BodyPart[] = [
  parseBodyPart({
    id: "universal_rubber_lip",
    name: "Universal rubber front lip",
    description: "Universal lip, 2.5m roll. Cut to size, turnilyo lang. Pang porma agad!",
    fits: "Universal, cut to fit",
    category: "front_lip",
    socket: "front_lip",
    assetPath: "/model/body/universal_rubber_lip.glb",
    compatibleTags: ["universal"],
    construction: "polyurethane",
    rarity: "common",
    fitment: 0.55,
    paint: { paintable: true, finish: "bare_plastic", mismatchColor: null },
    market: { priceRangePhp: [800, 1500], conditionRange: [0.5, 1] },
    effects: { weightKg: 1.5, drag: 0, downforce: 0.005, cooling: 0, reputation: 1 },
  }),
  // Sign-shop special: aluminium composite panel with carbon vinyl, on threaded-rod struts.
  parseBodyPart({
    id: "acp_chin_splitter",
    name: "ACP chin splitter (carbon vinyl)",
    description: "Custom chin, ACP board with carbon vinyl. Matibay, sumayad na sa humps pero ok pa.",
    fits: "90s sedans, drill mount",
    category: "chin",
    socket: "chin",
    assetPath: "/model/body/acp_chin_splitter.glb",
    compatibleTags: ["sedan", "hatchback"],
    construction: "aluminium",
    rarity: "common",
    fitment: 0.6,
    paint: { paintable: false, finish: "fake_carbon", mismatchColor: null },
    market: { priceRangePhp: [1200, 2200], conditionRange: [0.35, 0.9] },
    effects: { weightKg: 3, drag: 0.005, downforce: 0.01, cooling: -0.04, reputation: 2 },
  }),
  parseBodyPart({
    id: "dalagan_fiberglass_skirts",
    name: "Dalagan side skirts, fiberglass",
    description: "Side skirts pang Dalagan, fiberglass. Primer na, may konting bitak sa dulo. Pair.",
    fits: "Banwa Dalagan",
    category: "side_skirt",
    socket: "side_skirts",
    assetPath: "/model/body/dalagan_fiberglass_skirts.glb",
    compatibleTags: ["banwa_dalagan"],
    construction: "fiberglass",
    rarity: "uncommon",
    fitment: 0.7,
    paint: { paintable: true, finish: "primer", mismatchColor: null },
    market: { priceRangePhp: [3500, 5500], conditionRange: [0.35, 0.9] },
    effects: { weightKg: 6, drag: -0.005, downforce: 0, cooling: 0, reputation: 2 },
  }),
  parseBodyPart({
    id: "dalagan_ducktail",
    name: "Dalagan ducktail spoiler",
    description: "Pull-out ducktail, color silver na. Double-tape lang, pero mahigpit.",
    fits: "Banwa Dalagan trunk lid",
    category: "spoiler",
    socket: "spoiler",
    assetPath: "/model/body/dalagan_ducktail.glb",
    compatibleTags: ["banwa_dalagan"],
    construction: "abs",
    rarity: "common",
    fitment: 0.85,
    paint: { paintable: true, finish: "body_color", mismatchColor: null },
    market: { priceRangePhp: [1800, 3000], conditionRange: [0.5, 1] },
    effects: { weightKg: 2, drag: 0.005, downforce: 0.005, cooling: 0, reputation: 2 },
  }),
  // Wider than the trunk, bolted through it. Mostly drag; the crowd at the gas station loves it.
  parseBodyPart({
    id: "marketplace_gt_wing",
    name: "GT wing 145cm (carbon look)",
    description: "GT wing, carbon look! Adjustable daw. Universal, drill mo lang ang trunk. Pang Tokyo Drift.",
    fits: "Universal, trunk drill",
    category: "spoiler",
    socket: "spoiler",
    assetPath: "/model/body/marketplace_gt_wing.glb",
    compatibleTags: ["universal"],
    construction: "abs",
    rarity: "uncommon",
    fitment: 0.4,
    paint: { paintable: true, finish: "fake_carbon", mismatchColor: null },
    market: { priceRangePhp: [4500, 8000], conditionRange: [0.4, 0.95] },
    effects: { weightKg: 7, drag: 0.08, downforce: 0.02, cooling: 0, reputation: 5 },
  }),
  parseBodyPart({
    id: "dalagan_primer_bumper",
    name: "Dalagan front bumper (primer)",
    description: "Replacement bumper, primer pa lang. Sprayan mo na lang, boss. Kumpleto clips.",
    fits: "Banwa Dalagan '94–'98",
    category: "front_bumper",
    socket: "bumper_front",
    assetPath: "/model/body/dalagan_primer_bumper.glb",
    compatibleTags: ["banwa_dalagan"],
    construction: "polyurethane",
    rarity: "common",
    fitment: 0.8,
    paint: { paintable: true, finish: "primer", mismatchColor: null },
    market: { priceRangePhp: [2500, 4000], conditionRange: [0.4, 0.9] },
    effects: { weightKg: 0, drag: 0, downforce: 0, cooling: 0.02, reputation: 0 },
  }),
  parseBodyPart({
    id: "dalagan_red_fender_fl",
    name: "Dalagan front-left fender (red)",
    description: "Pull-out fender galing sa pula na Dalagan. Walang kalawang, halos. Ikaw na bahala sa pintura.",
    fits: "Banwa Dalagan, driver side front",
    category: "fender",
    socket: "fender_fl",
    assetPath: "/model/body/dalagan_fender_fl.glb",
    compatibleTags: ["banwa_dalagan"],
    construction: "steel",
    rarity: "common",
    fitment: 0.75,
    paint: { paintable: true, finish: "mismatched", mismatchColor: "#8e2a2a" },
    market: { priceRangePhp: [1200, 2200], conditionRange: [0.45, 0.85] },
    effects: { weightKg: 0, drag: 0, downforce: 0, cooling: 0, reputation: -1 },
  }),
  parseBodyPart({
    id: "vented_carbon_look_hood",
    name: "Vented hood, carbon look",
    description: "Fiberglass hood, carbon look, may vent. Kasama hood pins. Gaan, pang drag!",
    fits: "Banwa Dalagan",
    category: "hood",
    socket: "hood",
    assetPath: "/model/body/vented_carbon_look_hood.glb",
    compatibleTags: ["banwa_dalagan"],
    construction: "fiberglass",
    rarity: "rare",
    fitment: 0.65,
    paint: { paintable: true, finish: "fake_carbon", mismatchColor: null },
    market: { priceRangePhp: [6500, 10000], conditionRange: [0.3, 0.9] },
    effects: { weightKg: -6, drag: 0, downforce: 0, cooling: 0.08, reputation: 3 },
  }),
];

const byId = new Map(BODY_PARTS.map((part) => [part.id, part]));

export const bodyPart = (id: string): BodyPart | undefined => byId.get(id);
