import { NullEngine } from '@babylonjs/core/Engines/nullEngine';
import { Scene } from '@babylonjs/core/scene';
import { Vector3 } from '@babylonjs/core/Maths/math.vector';
import { afterEach, expect, it } from 'vitest';
import { ChaseCamera } from './ChaseCamera';
import { ChapterCamera } from './ChapterCamera';
import type { PlayerVehicle } from '../vehicles/PlayerVehicle';
import type { PlayerModes } from '../player/PlayerModes';
import type { DialogueController } from '../social/DialogueController';
import type { RuntimeBootstrap } from '@/game-core/persistence/RuntimeBootstrap';
let engine: NullEngine | null = null;
afterEach(() => { engine?.dispose(); engine = null; });
it('frames a workshop conversation, returns to gameplay, and honors reduced motion', () => {
 engine = new NullEngine(); const scene = new Scene(engine);
 const car = { position: new Vector3(16, 0, 158), forward: new Vector3(0, 0, 1), speed: 0 };
 const chase = new ChaseCamera(scene, car);
 const modes = { mode: 'walking', position: new Vector3(16, 0, 158) };
 const dialogue = { activeDialogueId: 'talyer_mang_boy' };
 const chapters = [{ id: 'chapter_1', currentBeatId: 'complete_first_job', markers: ['choose_origin', 'meet_mang_boy'], completedAt: null }];
 const director = new ChapterCamera(chase, car as PlayerVehicle, modes as PlayerModes, dialogue as DialogueController, () => chapters as RuntimeBootstrap['chapters']);
 const live = chase.camera.position.clone();
 director.update(.4);
 expect(Vector3.Distance(chase.camera.position, live)).toBeGreaterThan(.5);
 dialogue.activeDialogueId = null as unknown as string;
 chase.snap(); director.update(2);
 expect(Vector3.Distance(chase.camera.position, live)).toBeLessThan(.01);
 chase.reducedMotion = true; dialogue.activeDialogueId = 'talyer_mang_boy'; chase.snap();
 director.update(2);
 expect(Vector3.Distance(chase.camera.position, live)).toBeLessThan(.01);
 director.dispose(); chase.dispose();
});
it('waits until the car stops before framing the validated setback', () => {
 engine = new NullEngine(); const scene = new Scene(engine);
 const car = { position: new Vector3(120, 0, 72), forward: new Vector3(0, 0, 1), speed: 15 };
 const chase = new ChaseCamera(scene, car);
 const modes = { mode: 'driving', position: car.position };
 const dialogue = { activeDialogueId: null };
 const chapters = [{ id: 'chapter_1', currentBeatId: 'finish_first_race', markers: [], completedAt: null }];
 const director = new ChapterCamera(chase, car as PlayerVehicle, modes as PlayerModes, dialogue as DialogueController, () => chapters as RuntimeBootstrap['chapters']);
 const moving = chase.camera.position.clone();
 chapters[0].currentBeatId = 'repair_daily'; director.update(4);
 expect(chase.camera.position.equals(moving)).toBe(true);
 car.speed = 0; director.update(.2);
 expect(Vector3.Distance(chase.camera.position, moving)).toBeGreaterThan(.1);
 director.dispose(); chase.dispose();
});
